## Assignment 4

Vivaldi Rinaldi

In [3]:
import pylab as pl
import pandas as pd
import numpy as np
#imports downloader


%pylab inline

import os

Populating the interactive namespace from numpy and matplotlib


In [130]:
# Get June 2017 Data
!wget https://s3.amazonaws.com/tripdata/201706-citibike-tripdata.csv.zip
!unzip 201706-citibike-tripdata.csv.zip
!mv 201706-citibike-tripdata.csv.zip $PUIDATA
!mv 201706-citibike-tripdata.csv $PUIDATA

--2018-10-17 20:42:04--  https://s3.amazonaws.com/tripdata/201706-citibike-tripdata.csv.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.160.45
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.160.45|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60394834 (58M) [application/x-www-form-urlencoded]
Saving to: ‘201706-citibike-tripdata.csv.zip’

201706-citibike-tri 100%[===================>]  57.60M  51.0MB/s    in 1.1s    

2018-10-17 20:42:05 (51.0 MB/s) - ‘201706-citibike-tripdata.csv.zip’ saved [60394834/60394834]

Archive:  201706-citibike-tripdata.csv.zip
  inflating: 201706-citibike-tripdata.csv  


In [148]:
df = pd.read_csv(os.getenv("PUIDATA") + "/201706-citibike-tripdata.csv")

In [149]:
df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [151]:
df['date'] = pd.to_datetime(df['starttime'])
df.head()

tripduration            starttime             stoptime  start station id  \
0          1397  2017-06-01 00:00:02  2017-06-01 00:23:19               515   
1          1103  2017-06-01 00:00:13  2017-06-01 00:18:37               488   
2          1810  2017-06-01 00:00:20  2017-06-01 00:30:31               461   
3          1760  2017-06-01 00:00:24  2017-06-01 00:29:45              2009   
4          2165  2017-06-01 00:00:33  2017-06-01 00:36:38               360   

         start station name  start station latitude  start station longitude  \
0          W 43 St & 10 Ave               40.760094               -73.994618   
1           W 39 St & 9 Ave               40.756458               -73.993722   
2           E 20 St & 2 Ave               40.735877               -73.982050   
3  Catherine St & Monroe St               40.711174               -73.996826   
4      William St & Pine St               40.707179               -74.008873   

   end station id          end station name  end station latitude  \
0            3285  W 87 St  & Amsterdam Ave             40.788390   
1             297           E 15 St & 3 Ave             40.734232   
2             465        Broadway & W 41 St             40.755136   
3             527           E 33 St & 2 Ave             40.744023   
4             474           5 Ave & E 29 St             40.745168   

   end station longitude  bikeid    usertype  birth year  gender  \
0             -73.974700   26642  Subscriber      1967.0       1   
1             -73.986923   25656  Subscriber      1981.0       1   
2             -73.986580   21023  Subscriber      1982.0       1   
3             -73.976056   25718  Subscriber      1973.0       2   
4             -73.986831   18691  Subscriber      1985.0       1   

                 date  
0 2017-06-01 00:00:02  
1 2017-06-01 00:00:13  
2 2017-06-01 00:00:20  
3 2017-06-01 00:00:24  
4 2017-06-01 00:00:33

In [ ]:
## Get Hour

In [152]:
df['hour'] = df['date'].dt.hour

In [153]:
df.head()

tripduration            starttime             stoptime  start station id  \
0          1397  2017-06-01 00:00:02  2017-06-01 00:23:19               515   
1          1103  2017-06-01 00:00:13  2017-06-01 00:18:37               488   
2          1810  2017-06-01 00:00:20  2017-06-01 00:30:31               461   
3          1760  2017-06-01 00:00:24  2017-06-01 00:29:45              2009   
4          2165  2017-06-01 00:00:33  2017-06-01 00:36:38               360   

         start station name  start station latitude  start station longitude  \
0          W 43 St & 10 Ave               40.760094               -73.994618   
1           W 39 St & 9 Ave               40.756458               -73.993722   
2           E 20 St & 2 Ave               40.735877               -73.982050   
3  Catherine St & Monroe St               40.711174               -73.996826   
4      William St & Pine St               40.707179               -74.008873   

   end station id          end station name  end station latitude  \
0            3285  W 87 St  & Amsterdam Ave             40.788390   
1             297           E 15 St & 3 Ave             40.734232   
2             465        Broadway & W 41 St             40.755136   
3             527           E 33 St & 2 Ave             40.744023   
4             474           5 Ave & E 29 St             40.745168   

   end station longitude  bikeid    usertype  birth year  gender  \
0             -73.974700   26642  Subscriber      1967.0       1   
1             -73.986923   25656  Subscriber      1981.0       1   
2             -73.986580   21023  Subscriber      1982.0       1   
3             -73.976056   25718  Subscriber      1973.0       2   
4             -73.986831   18691  Subscriber      1985.0       1   

                 date  hour  
0 2017-06-01 00:00:02     0  
1 2017-06-01 00:00:13     0  
2 2017-06-01 00:00:20     0  
3 2017-06-01 00:00:24     0  
4 2017-06-01 00:00:33     0

In [154]:
df.hour.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### Get Day data

In [155]:
day = df.loc[(df.hour >= 7) & (df.hour <= 20) ]

In [156]:
day.head()

tripduration            starttime             stoptime  \
3117           430  2017-06-01 07:00:02  2017-06-01 07:07:12   
3118           853  2017-06-01 07:00:01  2017-06-01 07:14:14   
3119          2016  2017-06-01 07:00:02  2017-06-01 07:33:39   
3120          1056  2017-06-01 07:00:04  2017-06-01 07:17:40   
3121           427  2017-06-01 07:00:08  2017-06-01 07:07:15   

      start station id         start station name  start station latitude  \
3117               340    Madison St & Clinton St               40.712690   
3118              3285   W 87 St  & Amsterdam Ave               40.788390   
3119              3383  Cathedral Pkwy & Broadway               40.804213   
3120               494            W 26 St & 8 Ave               40.747348   
3121               359         E 47 St & Park Ave               40.755103   

      start station longitude  end station id            end station name  \
3117               -73.987763             315    South St & Gouverneur Ln   
3118               -73.974700            3400      E 110 St & Madison Ave   
3119               -73.966991             379             W 31 St & 7 Ave   
3120               -73.997236             473  Rivington St & Chrystie St   
3121               -73.974987             477             W 41 St & 8 Ave   

      end station latitude  end station longitude  bikeid    usertype  \
3117             40.703554             -74.006702   28129  Subscriber   
3118             40.796153             -73.947821   25179  Subscriber   
3119             40.749156             -73.991600   27721  Subscriber   
3120             40.721101             -73.991925   25032  Subscriber   
3121             40.756405             -73.990026   28526  Subscriber   

      birth year  gender                date  hour  
3117      1988.0       1 2017-06-01 07:00:02     7  
3118      1990.0       2 2017-06-01 07:00:01     7  
3119      1967.0       2 2017-06-01 07:00:02     7  
3120      1970.0       1 2017-06-01 07:00:04     7  
3121      1986.0       1 2017-06-01 07:00:08     7

In [157]:
day.hour.unique()

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### Get night data

In [160]:
night = df.loc[(df.hour <= 7)].append(df.loc[(df.hour >= 20)])
night.hour.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7, 20, 21, 22, 23])

In [161]:
night.head()

tripduration            starttime             stoptime  start station id  \
0          1397  2017-06-01 00:00:02  2017-06-01 00:23:19               515   
1          1103  2017-06-01 00:00:13  2017-06-01 00:18:37               488   
2          1810  2017-06-01 00:00:20  2017-06-01 00:30:31               461   
3          1760  2017-06-01 00:00:24  2017-06-01 00:29:45              2009   
4          2165  2017-06-01 00:00:33  2017-06-01 00:36:38               360   

         start station name  start station latitude  start station longitude  \
0          W 43 St & 10 Ave               40.760094               -73.994618   
1           W 39 St & 9 Ave               40.756458               -73.993722   
2           E 20 St & 2 Ave               40.735877               -73.982050   
3  Catherine St & Monroe St               40.711174               -73.996826   
4      William St & Pine St               40.707179               -74.008873   

   end station id          end station name  end station latitude  \
0            3285  W 87 St  & Amsterdam Ave             40.788390   
1             297           E 15 St & 3 Ave             40.734232   
2             465        Broadway & W 41 St             40.755136   
3             527           E 33 St & 2 Ave             40.744023   
4             474           5 Ave & E 29 St             40.745168   

   end station longitude  bikeid    usertype  birth year  gender  \
0             -73.974700   26642  Subscriber      1967.0       1   
1             -73.986923   25656  Subscriber      1981.0       1   
2             -73.986580   21023  Subscriber      1982.0       1   
3             -73.976056   25718  Subscriber      1973.0       2   
4             -73.986831   18691  Subscriber      1985.0       1   

                 date  hour  
0 2017-06-01 00:00:02     0  
1 2017-06-01 00:00:13     0  
2 2017-06-01 00:00:20     0  
3 2017-06-01 00:00:24     0  
4 2017-06-01 00:00:33     0

In [162]:
day.tripduration.mean()

1058.7148316825796

In [163]:
len(day)

1513955

In [164]:
night.tripduration.mean()

1095.9263363289522

In [165]:
len(night)

378219

#### KS Test

In [166]:
import scipy.stats

Null Hypothesis: The distribution of trip duration during the day is the same to the distribution to trip duration at night


In [167]:
ks = scipy.stats.ks_2samp(day.tripduration, night.tripduration)
print (ks)

Ks_2sampResult(statistic=0.046228686980984812, pvalue=0.0)


Reject the null - Distribution of trip duration during the day is different than distribution of trip during the night.

#### Pearson's Test

Null Hypothesis - There is no realtionship between trip duration at night and day 

In [172]:
pt = scipy.stats.pearsonr(day.tripduration.sample(1000), night.tripduration.sample(1000))
print (pt)

(-0.0094062231396268674, 0.76640128200533586)


Null Holds - There is no relationship between trip duration at night and day

#### Spearman's Test

Null Hypothesis - There is no realtionship between trip duration at night and day 

In [173]:
pt = scipy.stats.spearmanr(day.tripduration.sample(1000), night.tripduration.sample(1000))
print (pt)

SpearmanrResult(correlation=-0.016934528711148245, pvalue=0.59272911038861098)


Null Holds - There is no relationship between trip duration at night and day